### ISSUE TITLE
NPM or yarn locking?

### ISSUE THREAD

**Issue by justwheel** [unicef/publicgoods-accelerator-guide#13]
# Summary

Decide to use NPM or Yarn for package management instead of using both

# Background

This repository uses two different JavaScript package managers, `npm` and `yarn`. The CI pipeline is set up to always run on one of their lock files if another one is not present, but `yarn` gets precedence over other lock files. To avoid dependency mismatching by maintaining two lock files of the same project, I propose only one package manager is used for consistency purposes across developer and production environments.

`yarn` log output:

`warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.`

# Details

**If `yarn`**:
* Delete `package-lock.json`
* Run `yarn upgrade && yarn lock`
* Commit changes

**If `npm`**:
* Delete `yarn.lock`
* Run `npm update && npm lock`
* Commit changes

# Outcome

- Consistent package set used in developer and production environments
- Simplify maintenance so two lock files don't need to be updated simultaneously

**Comment by lacabra** [comment]
@jwflory: there is no `package-lock.json` committed to this repo, review the files on the `main` branch, and you'll see there is none. Maybe you inadvertently run `npm i` in one of your feature branches, which created the conflict that you are reporting?

I'm tagging this as `invalid`, and I will let you comment/close otherwise.

Thanks!

**Comment by justwheel** [comment]
@lacabra Right. I used an alias which called `npm i`. I realized after writing the commit message that `package-lock.json` wasn't in the repo, to begin with. I [added it](https://github.com/unicef/publicgoods-accelerator-guide/blob/main/.gitignore#L2) to the `.gitignore` to prevent the mistake next time.
